### PR TITLE
Crawl response to find links

### PR DESCRIPTION
**Pull request by barryvdh**
This scans the content to add all links. This fixes the wrong assets with merging etc ( #3).

Probably needs some A/B testing to see if what the performance impact is on this vs benefit over merging/minifying alone.

### CODE REVIEW

**Comment by barryvdh** [comment]
Also pushed images now, not sure if that's good for a lot of images?

**Comment by jissereitsma** [comment]
Looks solid to me. It is a different approach and might actually be smarter to make sure all of the appropriate files are "linked". Additionally, this might be working better with Full Page Cache being enabled. Unfortunately I don't have time to test this, so I will just merge your super-power-driven code instead.

**Comment by barryvdh** [comment]
I think you need to setup you Packagist webhook, as it's not updated yet. Or might be that github is not yet 100%

**Comment by jissereitsma** [comment]
Hmm, strange. Might it be because I changed the version just through the GitHub GUI. Anyway, Packagist is up2date as well with version 0.0.2. Thanks for the awesome work!

**Pull request merged**
